# Config.yml for EssentialsPro
motd:
  default: '&a[Welcome to &eOur &fMinecraft &bServer!&a]'
  custom: "Test"

# This is where the spawn is saved
spawn:

# Custom messages for players joining and leaving
joinMessage: "<yellow>[+] <green>{player} <yellow>has joined the server!"
leaveMessage: "<red>[-] <gray>{player} <red>has left the server!"

# Modify what people see when they die
death_messages:
  FALL: "[player] took a leap of faith!"
  DROWN: "[player] forgot to breathe!"
  BLOCK_EXPLOSION: "[player] went out with a bang!"
  CONTACT: "[player] was pricked to death. Cacti 1 - [Player] 0."
  CRAMMING: "[player] learned that personal space is important."
  CUSTOM: "[player] met a mysterious end."
  DRAGON_BREATH: "[player] couldn't handle the dragon's fiery breath!"
  DROWNING: "[player] forgot they weren't a fish."
  DRYOUT: "[player] dried up like an old sponge."
  ENTITY_ATTACK: "[player] was defeated in battle."
  ENTITY_EXPLOSION: "[player] got too close for comfort."
  ENTITY_SWEEP_ATTACK: "[player] was swiped away!"
  FALL: "[player] believed they could fly. They were mistaken."
  FALLING_BLOCK: "Gravity dropped a surprise on [player]!"
  FIRE: "[player] played with fire and got burned."
  FIRE_TICK: "[player] is now a crispy critter."
  FLY_INTO_WALL: "[player] forgot how to brake!"
  HOT_FLOOR: "[player] now knows why the floor is lava."
  LAVA: "[[player] took a hot bath and regretted it."
  LIGHTNING: "[player] got a shocking surprise from the sky!"
  MAGIC: "[player] couldn't escape the arcane forces."
  MELTING: "[player] couldn't stand the heat!"
  POISON: "[player] felt the deadly sting of poison."
  PROJECTILE: "[player] was the target of a sharpshooter."
  STARVATION: "[player] forgot to pack a lunch."
  SUFFOCATION: "[player] couldn't find their way out."
  SUICIDE: "[player] decided to check out."
  THORNS: "[player] got a prickly surprise!"
  VOID: "[player] fell into the abyss."
  WITHER: "[player] withered away."