# Config.yml for EssentialsPro
motd:
  default: '&a[Welcome to &eOur &fMinecraft &bServer!&a]'
  custom: "Test"

# This is where the spawn is saved
spawn:

# Custom messages for players joining and leaving
joinMessage: "<yellow>[+] <green>{player} <yellow>has joined the server!"
leaveMessage: "<red>[-] <gray>{player} <red>has left the server!"

# Modify what people see when they die
death_messages:
  FALL: "<yellow>[player]</yellow> took a leap of faith!"
  DROWN: "<blue>[player]</blue> forgot to breathe!"
  BLOCK_EXPLOSION: "<red>[player]</red> went out with a bang!"
  CONTACT: "<green>[player]</green> was pricked to death. <italic>Cacti 1 - [player] 0.</italic>"
  CRAMMING: "<gray>[player]</gray> learned that personal space is important."
  CUSTOM: "<gold>[player]</gold> met a mysterious end."
  DRAGON_BREATH: "<red>[player]</red> couldn't handle the dragon's fiery breath!"
  DROWNING: "<blue>[player]</blue> forgot they weren't a fish."
  DRYOUT: "<yellow>[player]</yellow> dried up like an old sponge."
  ENTITY_ATTACK: "<red>[player]</red> was defeated in battle."
  ENTITY_EXPLOSION: "<dark_red>[player]</dark_red> got too close for comfort."
  ENTITY_SWEEP_ATTACK: "<gray>[player]</gray> was swiped away!"
  FALL: "<yellow>[player]</yellow> believed they could fly. <italic>They were mistaken.</italic>"
  FALLING_BLOCK: "<gold>Gravity</gold> dropped a surprise on <yellow>[player]</yellow>!"
  FIRE: "<red>[player]</red> played with fire and got burned."
  FIRE_TICK: "<dark_red>[player]</dark_red> is now a crispy critter."
  FLY_INTO_WALL: "<gray>[player]</gray> forgot how to brake!"
  HOT_FLOOR: "<red>[player]</red> now knows why the floor is lava."
  LAVA: "<dark_red>[player]</dark_red> took a hot bath and regretted it."
  LIGHTNING: "<yellow>[player]</yellow> got a shocking surprise from the sky!"
  MAGIC: "<aqua>[player]</aqua> couldn't escape the arcane forces."
  MELTING: "<gold>[player]</gold> couldn't stand the heat!"
  POISON: "<green>[player]</green> felt the deadly sting of poison."
  PROJECTILE: "<red>[player]</red> was the target of a sharpshooter."
  STARVATION: "<gray>[player]</gray> forgot to pack a lunch."
  SUFFOCATION: "<dark_gray>[player]</dark_gray> couldn't find their way out."
  SUICIDE: "<gray>[player]</gray> decided to check out."
  THORNS: "<green>[player]</green> got a prickly surprise!"
  VOID: "<dark_purple>[player]</dark_purple> fell into the abyss."
  WITHER: "<dark_gray>[player]</dark_gray> withered away."